### ISSUE TITLE
Consider adding Start-Sleep under "Do" loop

### ISSUE THREAD

**Issue by awonglk** [kavierkoo/Shutdown-Hibernate-PC-via-IFTTT-through-Amazon-Alexa#1]
With the script as is.. it's chewing up >10% CPU cycles considering running the "Do" loop.  Presumably, there was a "Start-Sleep" statement before and was removed. Adding "Start-Sleep -Seconds $SleepTime" resolved the excessive CPU usage issue.

**Comment by kavierkoo** [comment]
Apologize for the late response, I overlooked the notification.
Also thanks for the info, added in the code in latest commit.

Kudos!
